### ISSUE TITLE
SliceSource example returns errors

### ISSUE THREAD

**Issue by mkoenig3** [bcdev/zappend#53]
Hi Norman,

I followed this example https://bcdev.github.io/zappend/guide/#slice-sources and defined a SliceSource to read temporal subsets of NetCDFs but don't get this script to run and receive the following errors.

```
import os
import xarray as xr
from zappend.api import zappend
from zappend.api import SliceSource
from zappend.api import to_slice_factories


class MarcelsSliceSource(SliceSource):
    def __init__(self, ctx, slice_path):
        super().__init__(ctx)
        self.slice_path = slice_path
        self.ds = None

    def get_dataset(self, min_hour=6, max_hour=18):
        self.ds = xr.open_dataset(self.slice_path)
        ds_hour = self.ds['time.hour']
        return self.ds.sel(time=(min_hour <= ds_hour <= max_hour))

    def dispose(self):
        if self.ds is not None:
            self.ds.close()
            self.ds = None
        if self.mean_ds is not None:
            self.mean_ds.close()
            self.mean_ds = None


zappend(os.listdir('temp'), target_dir='OA_GRIDDED_WATER_LEVELS.zarr', slice_source=__main__.MarcelsSliceSource)
```

```
python my_script.py
```

returns

```
Traceback (most recent call last):
  File "/home/marcel/zappend_test.py", line 34, in <module>
    zappend(os.listdir('temp'), target_dir='OA_GRIDDED_WATER_LEVELS.zarr', slice_source=__main__.MarcelsSliceSource)
                                                                                        ^^^^^^^^
NameError: name '__main__' is not defined. Did you mean: '__name__'?
```

I also tried

```
zappend(os.listdir('temp'), target_dir='OA_GRIDDED_WATER_LEVELS.zarr', slice_source=MarcelsSliceSource)
```

but received
```
Traceback (most recent call last):
  File "/home/marcel/miniforge3/envs/xcube/lib/python3.11/site-packages/zappend/config/config.py", line 44, in validate_config
    jsonschema.validate(config, CONFIG_SCHEMA_V1)
  File "/home/marcel/miniforge3/envs/xcube/lib/python3.11/site-packages/jsonschema/validators.py", line 1312, in validate
    raise error
jsonschema.exceptions.ValidationError: <class '__main__.MarcelsSliceSource'> is not of type 'string'

Failed validating 'type' in schema['properties']['slice_source']:
    {'description': 'The fully qualified name of a class or function that '
                    'provides a slice source for each slice item. If a '
                    'class is given, it must be  derived from '
                    '`zappend.api.SliceSource`. If a function is given, it '
                    'must return an instance of  '
                    '`zappend.api.SliceSource`. Refer to the user guide '
                    'for more information.',
     'minLength': 1,
     'type': 'string'}

On instance['slice_source']:
    <class '__main__.MarcelsSliceSource'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marcel/zappend_test.py", line 34, in <module>
    zappend(os.listdir('temp'), target_dir='OA_GRIDDED_WATER_LEVELS.zarr', slice_source=MarcelsSliceSource)
  File "/home/marcel/miniforge3/envs/xcube/lib/python3.11/site-packages/zappend/api.py", line 65, in zappend
    processor = Processor(config, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/miniforge3/envs/xcube/lib/python3.11/site-packages/zappend/processor.py", line 40, in __init__
    validate_config(config)
  File "/home/marcel/miniforge3/envs/xcube/lib/python3.11/site-packages/zappend/config/config.py", line 46, in validate_config
    raise ValueError(
ValueError: Invalid configuration: <class '__main__.MarcelsSliceSource'> is not of type 'string' for slice_source

```

**Comment by forman** [comment]
Please try

```
zappend(os.listdir('temp'), target_dir='OA_GRIDDED_WATER_LEVELS.zarr', slice_source="__main__.MarcelsSliceSource")
```

which passes your class via qualified name.

**Comment by mkoenig3** [comment]
Thanks, this solved the issue!
